name: Deploy firebase functions
on:
  push:
    branches: [feat/mono-repo]

jobs:
  build-and-deploy:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"
      
      - name: List files in current directory
        run: ls -R

      - name: create-json
        id: create-json
        uses: jsdaniell/create-json@1.1.2
        with:
          name: "credentials.json"
          json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
     
      - name: List files in current directory
        run: ls -R

      - name: Set environment variable with path to credentials.json
        run: echo "GOOGLE_APPLICATION_CREDENTIALS=$(readlink -f credentials.json)" >> $GITHUB_ENV
      
      - name: Install dependencies
        run: yarn

      - name: Install firebase tools
        run: yarn global add firebase firebase-tools

      - name: Build
        run: cd functions && yarn run deploy
