name: Jest Coverage Report with Annotations (CI)
on:
  pull_request:
    branches:
      - dev
jobs:
  coverage_report:
    name: Jest Coverage Report
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v2
      - name: Get Threshold
        id: threshold
        uses: notiz-dev/github-action-json-property@release
        with:
          path: "./web/jest.config.json"
          prop_path: "coverageThreshold.global.statements"

      - name: Install dependencies
        run: yarn

      - name: Test and generate coverage report
        uses: artiomtr/jest-coverage-report-action@v2.0-rc.4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          threshold: ${{steps.threshold.outputs.prop}}
          package-manager: yarn
          custom-title: Jest Coverage Report
          working-directory: "./web"
